In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import numpy as np
my_list = [10,20,30]
arr = np.array(my_list)
print(arr.dtype)
print(arr.shape)

int64
(3,)


In [9]:
list_of_lists = [[5, 10, 15], [20, 25, 30], [35, 40,45]]
arr_1 = np.array(list_of_lists)
print(arr_1.dtype)
print(arr_1.shape)

int64
(3, 3)


In [10]:
arr_1

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [15]:
import numpy as np
# (Start, Stop, Step)
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])